force-app/main/default/objects/Maintenance_Part__c/Maintenance_Part__c.object-meta.xml
<CustomObject>
    <label>Maintenance Part</label>
    <nameField>
        <label>Maintenance Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Part__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <label>Maintenance Request</label>
    <referenceTo>Maintenance_Reuest__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Part_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Part_Inventory__c</fullName>
    <label>Part Inventory</label>
    <referenceTo>Part_Inventory__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Qty_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Qty_Utilized__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Utilized</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Reuest__c/Maintenance_Reuest__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Maintenance Reuest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Reuest__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/Part_Inventory__c.object-meta.xml
<CustomObject>
    <label>Part Inventory</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Inventory__c/fields/Qty_In_Stock__c.field-meta.xml
<CustomField>
    <fullName>Qty_In_Stock__c</fullName>
    <label>Qty In Stock</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaintenancePartTriggerHelperAllDataTest.cls
/**
 * @description       : MaintenancePartTriggerHelper Test Class with see all data.
 * @author            : fpanara
 * @group             : 
 * @last modified on  : 09-26-2021
 * @last modified by  : fpanara
**/
@isTest
private class MaintenancePartTriggerHelperAllDataTest {
    @IsTest(SeeAllData=true)
    static void afterInsertWithSeeAllData(){

        Account act = new Account(Name = 'Test Account');
        insert act;

        Contact con = new Contact(LastName = 'Test Contact', AccountId = act.Id);
        insert con;

        Vehicle__c vehicle = new Vehicle__c(Contact__c = con.Id, Name = 'Test Vehicle', Make__c = 'TATA', Model__c = 'Test MOdel');
        insert vehicle;

        Maintenance_Reuest__c maintenanceRequest = new Maintenance_Reuest__c(Vehicle__c = vehicle.Id);
        insert maintenanceRequest;

        Part_Inventory__c partInventory = new Part_Inventory__c(Name = 'Child Part', Qty_In_Stock__c = 100, Min_Qty_Reminder__c = 5);
        insert partInventory;

        Maintenance_Part__c maintenancePart = new Maintenance_Part__c(Maintenance_Request__c = maintenanceRequest.Id, Part_Inventory__c = partInventory.Id, Qty_Utilized__c = 98);
        Test.startTest();
        insert maintenancePart; 
        Test.stopTest();

        System.assertEquals(partInventory.Qty_In_Stock__c - maintenancePart.Qty_Utilized__c, 2);
    }
}