force-app/main/default/objects/Maintenance_Part__c/Maintenance_Part__c.object-meta.xml
<CustomObject>
    <label>Maintenance Part</label>
    <nameField>
        <label>Maintenance Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Part__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <label>Maintenance Request</label>
    <referenceTo>Maintenance_Reuest__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Part_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Part_Inventory__c</fullName>
    <label>Part Inventory</label>
    <referenceTo>Part_Inventory__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Qty_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Qty_Utilized__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Utilized</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Reuest__c/Maintenance_Reuest__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Maintenance Reuest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Reuest__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/Part_Inventory__c.object-meta.xml
<CustomObject>
    <label>Part Inventory</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Inventory__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Part_Inventory__c</referenceTo>
    <relationshipLabel>Child Parts</relationshipLabel>
    <relationshipName>Child_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/fields/Qty_In_Stock__c.field-meta.xml
<CustomField>
    <fullName>Qty_In_Stock__c</fullName>
    <label>Qty In Stock</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaintenancePartTriggerHelperTest.cls
/**
 * @description       : 
 * @author            : fpanara
 * @group             : 
 * @last modified on  : 09-26-2021
 * @last modified by  : fpanara
**/
@isTest
public class MaintenancePartTriggerHelperTest {
    @testsetup static void dataSetup(){
    Account act = new Account(Name = 'Test Account');
    insert act;

    Contact con = new Contact(LastName = 'Test Contact', AccountId = act.Id);
    insert con;

    Vehicle__c vehicle = new Vehicle__c(Contact__c = con.Id, Name = 'Test Vehicle', Make__c = 'TATA', Model__c = 'Test MOdel');
    insert vehicle;
        
        List<Maintenance_Reuest__c> maintenanceRequestList = new List<Maintenance_Reuest__c>();
        for(integer i = 1; i<= 2; i++){
         Maintenance_Reuest__c maintenanceRequest = new Maintenance_Reuest__c(Vehicle__c = vehicle.Id);
        maintenanceRequestList.add(maintenanceRequest);
    }
    insert maintenanceRequestList;

    List<Part_Inventory__c> objParentPartInventoryList = new List<Part_Inventory__c>();
    //List<Part_Inventory__c> objChildPartInventoryList = new List<Part_Inventory__c>();
    
    for(integer i = 1; i<= 2; i++){
        Part_Inventory__c partInventory = new Part_Inventory__c(Name = 'Parent Part ' + i, Qty_In_Stock__c = 100, Min_Qty_Reminder__c = 5);
        objParentPartInventoryList.add(partInventory);
    }
    insert objParentPartInventoryList;

    
        Part_Inventory__c partInventory = new Part_Inventory__c(Name = 'Child Part', Qty_In_Stock__c = 400, Min_Qty_Reminder__c = 5, Parent__c = objParentPartInventoryList[1].Id, Child_Part_Qty__c = 5);
        insert partInventory;
    }

    @istest static void afterInsertAfterUpdatePosisiveTest(){

        List<Maintenance_Reuest__c> maintenanceRequestList = [SELECT Id FROM Maintenance_Reuest__c];
        List<Part_Inventory__c>  parentPartInventoryList = [SELECT ID, Qty_In_Stock__c, Min_Qty_Reminder__c, Parent__c, Child_Part_Qty__c FROM Part_Inventory__c WHERE Parent__c = null];
        List<Part_Inventory__c>  childPartInventoryList = [SELECT ID, Qty_In_Stock__c, Min_Qty_Reminder__c, Parent__c, Child_Part_Qty__c FROM Part_Inventory__c WHERE Parent__c != null];
        
        //Without depadent part
        Maintenance_Part__c maintenancePart = new Maintenance_Part__c(Maintenance_Request__c = maintenanceRequestList[0].Id, Part_Inventory__c = parentPartInventoryList[1].Id, Qty_Utilized__c = 10);
        Test.startTest();
        insert maintenancePart;        
        
        System.assertEquals(parentPartInventoryList[1].Qty_In_Stock__c - maintenancePart.Qty_Utilized__c, 90);

        maintenancePart.Qty_Utilized__c = 20;
        update maintenancePart;
        Test.stopTest();

        System.assertEquals(parentPartInventoryList[1].Qty_In_Stock__c - maintenancePart.Qty_Utilized__c, 80);
    }

        @istest static void afterInsertAfterUpdateNegativeTest(){

        List<Maintenance_Reuest__c> maintenanceRequestList = [SELECT Id FROM Maintenance_Reuest__c];
        List<Part_Inventory__c>  parentPartInventoryList = [SELECT ID, Qty_In_Stock__c, Min_Qty_Reminder__c, Parent__c, Child_Part_Qty__c FROM Part_Inventory__c WHERE Parent__c = null];
        List<Part_Inventory__c>  childPartInventoryList = [SELECT ID, Qty_In_Stock__c, Min_Qty_Reminder__c, Parent__c, Child_Part_Qty__c FROM Part_Inventory__c WHERE Parent__c != null];
        
        //Parent part maintenance request
        Maintenance_Part__c maintenancePart = new Maintenance_Part__c(Maintenance_Request__c = maintenanceRequestList[0].Id, Part_Inventory__c = parentPartInventoryList[0].Id, Qty_Utilized__c = 5);
        Test.startTest();
        insert maintenancePart;
        System.assertEquals(parentPartInventoryList[1].Qty_In_Stock__c - maintenancePart.Qty_Utilized__c, 95);
            
        //Adding 5
        maintenancePart.Qty_Utilized__c = 10;
        update maintenancePart;
        System.assertEquals(parentPartInventoryList[1].Qty_In_Stock__c - maintenancePart.Qty_Utilized__c, 90);

        //Removing 5
        maintenancePart.Qty_Utilized__c = 5;
        update maintenancePart;
        System.assertEquals(parentPartInventoryList[1].Qty_In_Stock__c - maintenancePart.Qty_Utilized__c, 95);
    
        //Checking minimum qty reminder on parent part
        maintenancePart.Qty_Utilized__c = 91;

                update maintenancePart;

                //System.assert(e.getMessage().contains('refill'));
            
        System.assertEquals(parentPartInventoryList[1].Qty_In_Stock__c - maintenancePart.Qty_Utilized__c, 9);
     
        //Low notification count excepation for parent part
        maintenancePart.Qty_Utilized__c = 100;
        try {
            update maintenancePart;
        }
        catch (Exception e) {
            //System.debug('Problem sending notification: ' + e.getMessage());
            System.assert(e.getMessage().contains('refill'));
        }
            
            //Child part maintenance request
        Maintenance_Part__c maintenancePart2 = new Maintenance_Part__c(Maintenance_Request__c = maintenanceRequestList[1].Id, Part_Inventory__c = parentPartInventoryList[1].Id, Qty_Utilized__c = 5);
        insert maintenancePart2;
            System.assertEquals(parentPartInventoryList[1].Qty_In_Stock__c - maintenancePart.Qty_Utilized__c, 0);
            
            
        //Checking minimum qty reminder on child part
        maintenancePart2.Qty_Utilized__c = 95;
            try{
                update maintenancePart;
            }
            Catch(Exception e){
                System.debug('Problem sending notification: ' + e.getMessage());
                System.assert(e.getMessage().contains('refill'));
            }
        
       
            
        
        
        Test.stopTest();
    }

    
}